const frases = [
    "Se você passa o domingo inteiro preocupado com a segunda, vale conversar sobre o que está tornando a semana tão pesada.",
    "Tente deixar algum espaço entre chegar em casa e começar outra obrigação.",
    "Quando até o lazer parece uma tarefa, talvez sua rotina esteja precisando de menos cobrança.",
    "O horário de dormir também precisa entrar na conversa sobre os prazos que você consegue cumprir.",
    "Se o trabalho continua pelo celular, o horário de descanso precisa ser discutido com a equipe.",
    "Antes de assumir outra tarefa em casa, veja se alguém pode dividir o que já está por sua conta.",
    "Você consegue rir com os amigos e ainda precisar conversar sobre algo que está doendo.",
    "“Não sei explicar, mas não estou bem” já é uma maneira de começar a pedir apoio.",
    "Escrever uma mensagem curta pode ajudar quando você ensaia um desabafo e desiste antes de falar.",
    "Na hora de marcar uma consulta, vale pedir ajuda com o telefone, o caminho ou a companhia.",
    "Quem cuida de um familiar também precisa de alguém que pergunte como foi o seu dia.",
    "Se a conversa sempre termina com você consolando os outros, vale dizer que hoje precisa ser ouvido.",
    "Combine com quem mora com você um tempo em que possa ficar quieto, sem ter de resolver nada.",
    "Na faculdade, peça uma conversa reservada quando precisar explicar que está difícil acompanhar as atividades.",
    "Na hora de avaliar seu cansaço, conte também as horas gastas no transporte e nas tarefas de casa.",
    "Ao receber um convite, considere quanto você precisa descansar naquela noite antes de confirmar presença.",
    "A preocupação com o dinheiro também precisa caber na conversa sobre como você está.",
    "Dá para sentir saudade de casa e, ao mesmo tempo, querer continuar morando onde você está.",
    "A falta de alguém pode apertar numa data comum, quando todos acham que você já se acostumou.",
    "O luto pode precisar de conversa muito depois que as mensagens de apoio param de chegar.",
    "Para contar algo delicado, procure alguém que costuma respeitar o que você compartilha.",
    "Durante um desabafo, você pode pedir: “Hoje eu queria que você só me ouvisse um pouco.”",
    "Quando alguém confiar uma dificuldade a você, pergunte antes de levar aquela história para outra conversa.",
    "Percebeu que uma brincadeira machucou? Interrompa a brincadeira e dê espaço para a pessoa explicar o que sentiu.",
    "Uma oferta de ajuda fica mais fácil de aceitar quando é específica: “Quer companhia para almoçar?”",
    "Leve anotações à consulta se costuma esquecer o que queria falar quando chega a sua vez.",
    "Quando uma orientação ficar confusa, peça que o profissional explique de outro jeito.",
    "Conte quando uma recomendação é difícil de seguir por causa do trabalho, do dinheiro ou de quem depende de você.",
    "O receio de ser julgado pode ser a primeira coisa que você conta ao profissional.",
    "Para começar uma conversa sobre como está, descreva uma parte do seu dia que ficou mais difícil.",
    "Ao procurar atendimento, considere também o trajeto e os horários que você consegue manter.",
    "Perguntar como funciona uma consulta antes de marcar pode esclarecer o que esperar daquele encontro.",
    "Mesmo nos dias em que você entrega tudo, vale perceber como fica depois que as obrigações acabam.",
    "Você pode dizer aos amigos que está passando por uma fase difícil e guardar os detalhes que prefere conversar em outro lugar.",
    "Ao voltar de um afastamento, tente combinar horários e tarefas que tornem a retomada possível.",
    "Uma semana melhor é uma oportunidade para perceber o que ajudou e qual apoio ainda faz falta.",
    "Conte ao profissional quando uma dificuldade reaparecer, inclusive depois de um período em que você estava melhor.",
    "Quando receber apoio, diga o que foi útil e o que acabou deixando você desconfortável.",
    "Quem está sempre disponível para ouvir também pode precisar encerrar uma conversa e descansar.",
    "Se acompanhar alguém está pesando, procure orientação e outras pessoas com quem dividir esse apoio.",
    "Ao oferecer ajuda, pergunte se a pessoa prefere conversar, fazer algo junto ou ter um pouco de espaço.",
    "Você pode silenciar um perfil mesmo gostando da pessoa que publica nele.",
    "Converse com pessoas próximas sobre como avisar quando estiver sem energia para responder às mensagens.",
    "Se o barulho do ambiente torna o dia mais difícil, vale conversar sobre um lugar mais tranquilo ou sobre pausas possíveis.",
    "Quando toda refeição acontece diante de uma tarefa, tente negociar um horário para comer com calma.",
    "Falar sobre racismo, assédio ou humilhação também faz parte de contar o que está afetando você.",
    "Numa conversa sobre sobrecarga no trabalho, leve exemplos dos prazos e das tarefas que estão difíceis de sustentar.",
    "Se pedir ajuda foi difícil uma vez, essa experiência pode ser contada na próxima tentativa.",
    "Um elogio à sua força pode receber uma resposta honesta: “Obrigado, mas estou precisando de ajuda com isso.”",
    "Guarde num lugar fácil os contatos de pessoas e serviços a que você pode recorrer num dia difícil.",
    "Para começar a estudar, escolha um assunto que caiba na próxima meia hora.",
    "Abra o arquivo e escreva três ideias, mesmo desorganizadas; você pode cuidar da forma depois.",
    "Antes de aceitar um compromisso, confira a semana inteira, incluindo deslocamentos e coisas que já prometeu.",
    "Uma resposta como “vou olhar minha agenda e te aviso” dá tempo para decidir com menos pressa.",
    "Anote onde parou antes de encerrar o trabalho; amanhã você terá um ponto de partida.",
    "Depois de um erro, escolha uma coisa para ajustar na próxima tentativa.",
    "Peça um exemplo quando uma crítica parecer vaga; fica mais fácil decidir o que fazer com ela.",
    "Ao avaliar um resultado, considere os recursos, o tempo e a ajuda que estavam disponíveis naquele momento.",
    "Você pode mudar de objetivo depois de conhecer melhor o caminho que ele exige.",
    "Antes de seguir um conselho, veja se ele considera seus horários, seu dinheiro e o que você quer.",
    "Aprender uma coisa nova inclui perguntar algo que os outros já parecem saber.",
    "Dá para continuar gostando de desenhar mesmo que seus desenhos nunca virem um portfólio.",
    "Ao receber um elogio, experimente agradecer antes de explicar por que acha que não merece tanto.",
    "Guarde um trabalho de que gostou para rever nos dias em que estiver duvidando de tudo o que faz.",
    "É possível ser iniciante numa atividade depois de passar anos sendo bom em outra.",
    "Se uma tarefa sempre fica para depois, observe onde você trava: começar, entender, decidir ou terminar.",
    "Faça um pedido de ajuda com tamanho definido: “Você consegue olhar este trecho comigo?”",
    "Explique seu limite dizendo o que é possível: “Hoje consigo ajudar por vinte minutos.”",
    "“Não vou conseguir” pode ser uma resposta honesta, sem precisar vir acompanhada de uma emergência inventada.",
    "Dê a si algum tempo antes de responder a um pedido feito em cima da hora.",
    "Ao pedir desculpas, diga o que pretende fazer diferente na próxima vez.",
    "Quando uma conversa esquentar, vocês podem combinar uma pausa e um horário para retomá-la.",
    "Preste atenção em como fica depois de um encontro; sua experiência também conta, mesmo quando os outros se divertiram.",
    "Um café em casa ou uma caminhada curta podem ser maneiras possíveis de manter uma amizade.",
    "Diga a um amigo quando gostou de algo que ele fez; as pessoas nem sempre sabem o que acertaram.",
    "Quando perguntarem por seus planos, conte a parte que você já se sente à vontade para compartilhar.",
    "Antes de se inscrever em outra atividade, veja em qual horário ela entraria na semana que você realmente tem.",
    "Inclua nos seus objetivos coisas que você quer viver, além das que precisa entregar.",
    "Se um prazo ficou inviável, avise cedo e proponha uma nova data que você consiga cumprir.",
    "Reserve no planejamento algum espaço para os atrasos que já fazem parte da sua rotina.",
    "Repare nas metas que você mantém apenas porque anunciou para outras pessoas.",
    "Você pode parar uma atividade de que deixou de gostar, mesmo tendo comprado todo o material.",
    "Ajuste o método de estudo aos seus horários, inclusive nos dias em que sobra pouco tempo.",
    "Uma anotação sobre o que funcionou hoje pode ser útil quando você precisar tentar de novo.",
    "Na revisão da semana, inclua algo que aprendeu a fazer com menos dificuldade.",
    "Deixe uma dúvida registrada e siga para outra parte quando ela estiver prendendo o trabalho inteiro e puder ser resolvida depois.",
    "Veja o que precisa sair da sua agenda para que uma nova prioridade encontre espaço.",
    "A roupa de que você gosta pode ser usada numa terça-feira qualquer.",
    "Fotografe também os dias de que gostou, mesmo que a casa estivesse bagunçada.",
    "Pergunte a si mesmo o que gostaria de fazer se não precisasse contar a ninguém depois.",
    "Você pode gostar de alguém e preferir encontros mais curtos com essa pessoa.",
    "Ao ouvir uma opinião sobre seus planos, reserve um tempo para decidir o que faz sentido para você.",
    "Um hábito novo precisa encontrar lugar num dia comum, com trabalho atrasado, louça e vontade de ficar no sofá.",
    "Retome uma atividade pela parte de que sente falta, respeitando o tempo que consegue dedicar agora.",
    "Peça companhia para resolver aquela pendência que você adia por não saber como começar.",
    "Depois de entregar um projeto trabalhoso, reserve um momento para comemorar do seu jeito.",
    "Escolha com cuidado de quem quer receber opinião sobre um projeto ainda inacabado.",
    "Você pode mandar “não entendi essa parte, consegue explicar?” sem pedir desculpas por estar aprendendo.",
    "Se o plano depende de você nunca adoecer, atrasar ou se cansar, vale rever o que ele está exigindo.",
    "“Ainda estou descobrindo” é uma resposta possível quando perguntam por um futuro que você ainda está tentando escolher."
]

const frase = document.getElementById("frase")
const icon = document.querySelector("img")

function gerador(){
    let num = Math.floor(Math.random() * frases.length)
    if (num < 50){
        icon.src = "public/mental-health.png"
    } else {
        icon.src = "public/faixa_amarela.png"
    }
    frase.textContent = frases[num]
}

window.onload = function() {
    gerador()
}